### ISSUE TITLE
打开 Windows 的 “任务视图” 导致壁纸接管立刻失效

### ISSUE THREAD

**Issue by Remik1r3n** [Candlest/ClassBoardSharp#5]
使用任一方法（触屏下从屏幕左侧边缘向右滑动、按 Win+Tab 快捷键、在任务栏上点击 “任务视图” 按钮）打开 Windows 10 的 “任务视图” 界面，均会导致壁纸接管立刻失效。

壁纸会（似乎是概率型的）消失，或者分离出一个窗口。

在我这里测试复现率似乎是 100%。

版本：[1.0.23.0819](https://github.com/Candlest/ClassBoardSharp/releases/tag/Release230819) https://github.com/Candlest/ClassBoardSharp/commit/a1034168cc1204bbe3d61608d42697f6a2ac1dbf

**Comment by Candlest** [comment]
感谢反馈，不过目前暂无与 Task View 相关的 API，采取的是[一个检测焦点窗口的笨方法](https://stackoverflow.com/questions/46653985/detect-wintab-task-view)。
原方法：
```C++
bool isTaskView() {
    //Get foreground window's name
    HWND fgWindow = GetForegroundWindow();
    TCHAR windowName[MAX_PATH] = L"";
    GetWindowText(fgWindow, windowName, MAX_PATH);
    //Compare with magic string name of Task View's window
    std::wstring nameStr(windowName);
    return nameStr == L"Task View";
}
```
仿写，每秒检查一次：
```C#
var fgwin = DllImports.GetForegroundWindow();
StringBuilder outText = new StringBuilder(256);
int a = DllImports.GetWindowText(fgwin, outText, outText.Capacity);
if(outText.ToString() == "任务视图" && (!hasMess))
{
    hasMess = true;
    MessageBox.Show(this, "检测到壁纸接管失效，确认后重新接管壁纸", "Class Board");
    initBackground();
}
```
**测试版本：Win10 LSTC 2019** ，不知是否可以在高版本 Win10下正常运行。

-----
已知 Bug ：由于用 [GetWindowTex](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowtexta) 检测任务视图，可能出现在不同语言环境下失效的问题，有待修复，虽然用这程序的大概都是SC区的。
